config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  #ROOT, first page to show
  root 'pages#home'
  
  # maps requests for the URL/pages/home to the about us action in the Pages controller.
  # By using GET we arrange for the route to respond to a GET request.
  # With this we generate a about us action inside the Pages controller, automatically
  # get a page at the address /pages/about us
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create' #signup route that responds to POST requests.
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #resources :reviews, only: [:create, :destroy]
  resources :reviews
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_review, only: [:show, :destroy]
    before_action :logged_in_user, only: [:create, :edit, :destroy]
    

    def index
        @reviews = Review.all
        if params[:search]
            @reviews = Review.search(params[:search]).order("created_at DESC")
        else
            @reviews = Review.all.order("created_at DESC")
        end
    end
    
    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            flash[:success] = "Review created!"
            redirect_to root_url
        else
            @feed_items = []
            render 'static_pages/home'
        end
    end
    
    def destroy
        @review.destroy
        flash[:success] = "Review deleted"
        redirect_to request.referrer || root_url
    end
    
    private

        # Use callbacks to share common setup or constraints between actions.
        def set_review
          @review = Review.find(params[:id])
        end
        
        
        def review_params
          params.require(:review).permit(:course, :year, :professor, :semester, :content, :user_id)
        end
        
        def correct_user
          @review = current_user.reviews.find_by(id: params[:id])
          redirect_to root_url if @review.nil?
        end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
  <%- #<%= link_to gravatar_for(review.user, size: 50), review.user %>
  <span class="user">
    <%- #<%= link_to review.user.name, review.user %>
    <b><%= review.course %></b>
  </span>
  <br><br>
  
  <span class="content"><%= review.content %></span>
  
  <br><br>
  <span class="information">
    <b>Professor: </b><%= review.professor %><br>
    <b>Year: </b><%= review.year %><br>
    <b>Semester: </b><%= review.semester %>
  </span>
  <br>
  <br>
  <span class="timestamp">Posted by <%= link_to review.user.name, review.user %>
    <%= time_ago_in_words(review.created_at) %> ago.
    
    <%- #DELETE FUNCTION %>
    <% if current_user?(review.user) %>
      <%= link_to "delete", review, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>
<hr>

app/views/reviews/index.html.erb
<% provide(:title, "Reviews") %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-8 col-md-offset-1">
  <h3>Reviews</h3>
  <p>These reviews are sorted so that the most recent reviews are on the top.</p>
    <%-#<%= render 'shared/all_reviews' %>
    <br>
  <div class="signup-now">
    To make a review you need to be <%= link_to "logged in", login_path %>! Don't have an account? <%= link_to "Sign up!", signup_path %>
  </div>  
  <br>
  <br>
 
  
  <%-#<%= THE SEARCH BAR %>
  
  <%= form_tag(reviews_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search for reviews by their coursename, professor, year or semester.." %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>


  <%-#<%= RENDERING SEARCH RESULTS %>
  <% if @reviews.blank? %>
    <p>There are no reviews containing the term(s) "<%= params[:search]  %>". 
    <%= link_to "Go Back?",   reviews_path %></p>
  <% else %>
      <%= render @reviews %>
  <% end %>

  <%-#<%= ALL THE REVIEWS %>  
  <% @reviews.each do |review| %>
    <%= render review %>
  <% end %>
</div>
</div>