config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  #ROOT, first page to show
  root 'pages#home'
  
  # maps requests for the URL/pages/home to the about us action in the Pages controller.
  # By using GET we arrange for the route to respond to a GET request.
  # With this we generate a about us action inside the Pages controller, automatically
  # get a page at the address /pages/about us
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create' #signup route that responds to POST requests.
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #resources :reviews, only: [:create, :destroy]
  resources :reviews
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    
    
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">CourseBuddies</a>
    by <a href="#/">My T. Nguyen</a> | Social Informatics, Kyoto Universty 2017.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo2.png", alt: "CourseBuddies logo"), root_path, id: "logo" %>
    <%- # link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path   %></li>
        <li><%= link_to "Reviews",   reviews_path %></li>
        
         <%- # LOGIN & SCROLL DOWN BAR %>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <%- # Everything that is in this file will be applied to all pages -%>
    
    <%-# We get the base title from app/helpers/application_helper- -%>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
  
    <%-# ASSETS AND STYLESHEETS -%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    <%-# renders the partial app/views/layouts/_shim.html.erb- -%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%-# renders the partial app/views/layouts/_header.html.erb- -%>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <%-# SHOWS MESSAGES (ERRORS OR ACCOMPLSHEMSNTS) -%>
      <% flash.each do |message_type, message| %>
      
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%-# This code is responsible for inserting the contents of each page into layout- -%>
      <%= yield %>
      
      <%-# Gets the debug box below -%>
      <%= debug(params) if Rails.env.development? %>
      
      <%-# renders FOOTER -%>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>